highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
paginate: 5
gems: [jekyll-paginate]
port: 4000
safe: true
url: http://superbderrick.github.io
author: Fábio Madeira

# edit this section with your information
# biomadeira.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: 
title: Derrick's Resume
name: Derrick,강진영
email: kang.derrick@gmail.com
email_full: kang.derrick@gmail.com
website: github.io/superbderrick
website_full: http://superbderrick.github.io
github: superbderrick
linkdin: https://www.linkedin.com/in/sensational/
# address: 'Enthusiast about how technology can be applied to improve daily life and for public welfare.
# and Trying to be good open source contributor.'


city: Seoul
country: South Korea
# detail: Interested Development Areas
# iOS Development (swift)  / Serverside (python & Django) / Computer vision (openGL , Metal)'