highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
paginate: 5
gems: [jekyll-paginate]
port: 4000
safe: true
url: http://superbderrick.github.io/Resume
author: Fábio Madeira

# edit this section with your information
# biomadeira.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /Resume/
title: Derrick's Resume
name: Derrick
email: kang.derrick@gmail.com
email_full: kang.derrick@gmail.com
website: github.io/superbderrick
website_full: http://superbderrick.github.io/Resume
github: superbderrick
linkdin: https://www.linkedin.com/in/sensational/
google_maps: 'https://www.google.co.kr/maps/place/%EA%B0%95%EB%82%A8%EC%97%AD/@37.497942,127.0254323,17z/data=!3m1!4b1!4m5!3m4!1s0x357ca1598c361b2b:0xdbf9af292beff3c!8m2!3d37.497942!4d127.027621'
address: gangnam
city: Seoul
country: South Korea
